[workspace]
members = [
    "days/01/01", "days/01/02",
    "days/02/01", "days/02/02",
]
resolver = "2"

[workspace.package]
version = "1.0.0"
edition = "2024"
rust-version = "1.91.1"

[workspace.dependencies]
serde = { version = "1.0", features = ["derive"] }
